version: "3.7"

services:
  algo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ghcr.io/mosesmc52/tsp-allocation-engine:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - ../.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
